CREATE DATABASE IF NOT EXISTS FahrzeugDB;
GRANT ALL PRIVILEGES ON FahrzeugDB.* TO 'admin' IDENTIFIED BY 'admin';
FLUSH PRIVILEGES;
USE FahrzeugDB;
DROP TABLE IF EXISTS fahrzeuge;
CREATE TABLE fahrzeuge (
	id INT NOT NULL AUTO_INCREMENT,
	fahrzeug_name VARCHAR(100) NOT NULL,
	fahrzeug_typ VARCHAR(100) NOT NULL,
	PRIMARY KEY ( id )
);